### PR TITLE
LPS-69666 Fixed merge logic in JournalUtil

### PR DESCRIPTION
**Pull request by SGM3**
Fixed an issue in JournalUtil merge algorithm that tried to merge empty elements with existing elements causing a IndexOutOfBoundsException

### CODE REVIEW

**Comment by SGM3** [comment]
This code is unused in master, but used current used in ee-7.0.x and ee-6.2.x. The goal is to backport this change to ee-7.0.x and ee-6.2.x.

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
Hi @SGM3,

please assign the LPP to me in the review status with the pull request linked as well.

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/jonathanmccann/com-liferay-journal/pull/8

**Pull request closed without merging**
