### PR TITLE
LPS 73142

### PR DESCRIPTION
**Pull request by JonathanAichler**
https://issues.liferay.com/browse/LPS-73142

Hey Sam,
I discovered this issue while investigating a related issue in 70x. To resolve the 70x issue, I will need to fix this issue in Master as well.

### CODE REVIEW

**Comment by SamZiemer** [comment]
Hi @JonathanAichler,

I'll be reviewing this fix now, however, there are a few issues I noticed before I started reviewing. When you submit an LPS for review that has an LPP associated with it, always change the LPP to the review status and assign it to me. LPPs assigned to me in the review status is one of the ways I use to track which pull requests have priority, and how many I need to do.

Also, any commit you are making must have an LPS number as the first part of the commit message. I will amend this commit but keep it in mind for future pull requests.

**Comment by SamZiemer** [comment]
Hi @JonathanAichler,
In the LPS, you need to add "Expected Results" and "Actual Results" sections. As of now, I have no idea what I am supposed to see when using the steps to reproduce you have listed on LPS-73142. Let me know when you have updated the LPS

**Comment by JonathanAichler** [comment]
Hi Sam,
Thanks for filling me in again on the review process. I have updated the Expected and Actual Results on the LPS.

**Comment by SamZiemer** [comment]
Forwarded to https://github.com/jonathanmccann/com-liferay-journal/pull/20

Please see https://github.com/SamZiemer/com-liferay-journal/commit/bc1e6351480888d1546ed584f1cc57121699b241, make sure you source format correctly.

**Pull request closed without merging**
